### ISSUE TITLE
Thunderstore release

### ISSUE THREAD

**Issue by Xenira** [toebeann/Tobey.UnityAudio#1]
I am using this plugin as a soft dependendency in my mod.

Would you consider creating a thunderstore.io release to make it easier to install as a dep. with other mods?

**Comment by toebeann** [comment]
Hey, thanks for the interest. I'll look into this.

**Comment by Xenira** [comment]
If it is something you are considering I can help with automatic deployment using gh actions.

**Comment by toebeann** [comment]
Which community would your mod be in? I would need to upload it to thunderstore for that specific community for your mod to be able to depend on it with thunderstore. Also, is there any specific configuration required for the game/community, or are the defaults set by UnityAudio fine?

**Comment by Xenira** [comment]
Community is Techtonica. https://thunderstore.io/c/techtonica/
As far as I know there are no specific configurations per community and the defaults should be fine.

Just need to set https://thunderstore.io/c/techtonica/p/BepInEx/BepInExPack/ as a dependenc (which I forgot in my release, now that I am thinking about it 😅)

**Comment by toebeann** [comment]
Here you go: https://thunderstore.io/c/techtonica/p/Tobey/UnityAudio/

Let me know if you have any problems :)
